quarkus.http.port=9090
elastic.username=elastic
elastic.password=s5HVQz7u7QZFTdUxN2ih
elastic.host=192.168.1.111
elastic.port=9200
elastic.index=plx-news-archive-1
duplicate.compare.firstField=title
duplicate.compare.secondField=documentPath