quarkus.http.port=9090
elastic.username=elastic
elastic.password=
elastic.host=192.168.1.211
elastic.port=9200
elastic.index=plx-uk-judicial
duplicate.compare.firstField=courtType
duplicate.compare.secondField=documentPath

# JVM Memory Settings
quarkus.native.additional-build-args=-J-Xmx4g,-J-Xms2g